export enum TipoGastronomia {
  RISTORANTE = "RISTORANTE",
  FORNO = "FORNO",
  ENOTECA = "ENOTECA",
  GELATERIA = "GELATERIA",
  OSTERIA = "OSTERIA",
  CAFFETTERIA = "CAFFETTERIA",
  MERCATO = "MERCATO"
}
